# Datos de rutas urbanas y rurales de Rapa Nui (Isla de Pascua)
# Coordenadas aproximadas reales de la isla.

IMG_MOAI = "https://images.unsplash.com/photo-1597240890437-6d9c2d4c16aa?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NDh8MHwxfHNlYXJjaHwxfHxFYXN0ZXIlMjBJc2xhbmQlMjBNb2FpJTIwc3RhdHVlJTIwbGFuZHNjYXBlfGVufDB8fHx8MTc4MzI4MzEyNXww&ixlib=rb-4.1.0&q=85"
IMG_TRAIL = "https://images.unsplash.com/photo-1782805332884-77a512becad7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2OTV8MHwxfHNlYXJjaHwxfHxSYXBhJTIwTnVpJTIwbGFuZHNjYXBlJTIwaGlrZSUyMHRyYWlsfGVufDB8fHx8MTc4MzI4MzEyNnww&ixlib=rb-4.1.0&q=85"
IMG_WATER = "https://images.unsplash.com/photo-1763490538690-5089ad94fc6b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1Nzl8MHwxfHNlYXJjaHwxfHxmcmVzaCUyMHNwcmluZyUyMHdhdGVyJTIwbmF0dXJhbCUyMHN0cmVhbXxlbnwwfHx8fDE3ODMyODMxMjV8MA&ixlib=rb-4.1.0&q=85"

WATER_POINTS = [
    {
        "id": "vai-1",
        "name": "Supermercado HE IVI",
        "lat": -27.1490,
        "lng": -109.4315,
        "type": "tienda",
        "description": "El supermercado más grande de Hanga Roa. Agua VAINATIVA embotellada, bloqueador e insumos para el trekking.",
    },
    {
        "id": "vai-2",
        "name": "Feria Municipal de Hanga Roa",
        "lat": -27.1486,
        "lng": -109.4308,
        "type": "tienda",
        "description": "Agua embotellada, fruta fresca local (piña, plátano) ideal para hidratarse en ruta.",
    },
    {
        "id": "vai-3",
        "name": "Almacenes Av. Atamu Tekena",
        "lat": -27.1445,
        "lng": -109.4295,
        "type": "tienda",
        "description": "Varios minimarkets a lo largo de la avenida principal. Última opción antes de salir a rutas rurales del norte.",
    },
    {
        "id": "vai-4",
        "name": "Kiosco Playa Anakena",
        "lat": -27.0737,
        "lng": -109.3238,
        "type": "tienda",
        "description": "Único punto de venta fuera de Hanga Roa. Agua, jugos y empanadas junto a la playa.",
    },
    {
        "id": "vai-5",
        "name": "Minimarket Sector Mataveri",
        "lat": -27.1580,
        "lng": -109.4360,
        "type": "tienda",
        "description": "Práctico para abastecerse antes de subir al Rano Kau u Orongo.",
    },
    {
        "id": "vai-6",
        "name": "Panadería HARAO TIRE",
        "lat": -27.1470,
        "lng": -109.4285,
        "type": "tienda",
        "description": "Pan fresco y agua VAINATIVA fría, ideal para armar tu colación antes de salir a la ruta.",
    },
    {
        "id": "vai-7",
        "name": "Locales de Rano Raraku",
        "lat": -27.1225,
        "lng": -109.2930,
        "type": "tienda",
        "description": "Locales de venta en el sector de la cantera Rano Raraku: agua VAINATIVA, jugos y snacks para el recorrido.",
    },
]

ROUTES = [
    # ---------------- URBANAS ----------------
    {
        "id": "circuito-hanga-roa",
        "name": "Circuito Histórico de Hanga Roa",
        "type": "urbana",
        "distance_km": 3.5,
        "duration_min": 60,
        "difficulty": "Fácil",
        "color": "#B35D4A",
        "image": IMG_MOAI,
        "summary": "Recorrido por el corazón del único pueblo de la isla: caleta, iglesia, feria y el complejo ceremonial Tahai.",
        "description": "Este paseo urbano registrado conecta los principales hitos de Hanga Roa, el único centro poblado de Rapa Nui. Comienza en la Caleta Hanga Roa Otai, donde los pescadores llegan con atún y kana kana al amanecer. Continúa por la Iglesia Santa Cruz, famosa por su iconografía tallada que fusiona el catolicismo con la cosmovisión rapanui, y la Feria Municipal con artesanía y frutas locales. El circuito termina en el Complejo Ceremonial Tahai, restaurado en 1974, con tres ahu y el famoso moai Ko Te Riku con ojos de coral: el mejor lugar de la isla para ver el atardecer.",
        "path": [
            [-27.1524, -109.4327], [-27.1499, -109.4335], [-27.1489, -109.4305],
            [-27.1470, -109.4300], [-27.1450, -109.4308], [-27.1420, -109.4295],
            [-27.1390, -109.4280], [-27.1355, -109.4265],
        ],
        "pois": [
            {"name": "Caleta Hanga Roa Otai", "type": "cultural", "lat": -27.1499, "lng": -109.4335, "description": "Caleta de pescadores con un moai solitario mirando al mar."},
            {"name": "Iglesia Santa Cruz", "type": "cultural", "lat": -27.1489, "lng": -109.4305, "description": "Tallados que mezclan santos católicos con el hombre-pájaro Tangata Manu."},
            {"name": "Feria Municipal", "type": "cultural", "lat": -27.1486, "lng": -109.4308, "description": "Artesanía en madera de toromiro, collares de conchas y fruta local."},
            {"name": "Complejo Ceremonial Tahai", "type": "moai", "lat": -27.1355, "lng": -109.4265, "description": "Ahu Vai Uri, Ahu Tahai y el moai Ko Te Riku con ojos restaurados."},
            {"name": "Museo Antropológico P. Sebastián Englert", "type": "arqueologico", "lat": -27.1335, "lng": -109.4245, "description": "El único ojo de moai original encontrado y tablillas Rongo Rongo."},
        ],
        "vai": {
            "recommended_liters": "1 litro por persona",
            "buy_point_ids": ["vai-1", "vai-2", "vai-3"],
            "tips": [
                "Compra agua VAINATIVA embotellada en el Supermercado HE IVI o en la Feria Municipal al inicio del circuito.",
                "El sol en la isla es intenso incluso con nubes: hidrátate cada 30 minutos.",
                "Prefiere botellas reutilizables; la isla tiene un delicado sistema de manejo de residuos.",
            ],
        },
    },
    {
        "id": "costanera-policarpo-toro",
        "name": "Costanera Policarpo Toro",
        "type": "urbana",
        "distance_km": 2.8,
        "duration_min": 45,
        "difficulty": "Fácil",
        "color": "#607D8B",
        "image": IMG_TRAIL,
        "summary": "Paseo costero por el borde mar de Hanga Roa: Playa Pea, Hanga Vare Vare y la caleta Hanga Piko.",
        "description": "La ruta costera urbana más popular de Hanga Roa recorre el borde del Pacífico desde Tahai hasta la caleta Hanga Piko. Pasarás por Playa Pea, una pequeña piscina natural de arena blanca donde los niños locales aprenden a nadar, y por Hanga Vare Vare, la gran explanada donde se celebra la fiesta Tapati Rapa Nui cada febrero. Los surfistas locales corren olas frente a la costanera todo el año. Ideal al atardecer, cuando el sol cae directamente frente a la costa oeste.",
        "path": [
            [-27.1355, -109.4265], [-27.1390, -109.4285], [-27.1420, -109.4300],
            [-27.1455, -109.4322], [-27.1499, -109.4335], [-27.1540, -109.4355],
            [-27.1573, -109.4374],
        ],
        "pois": [
            {"name": "Playa Pea", "type": "playa", "lat": -27.1505, "lng": -109.4340, "description": "Piscina natural protegida, perfecta para un chapuzón urbano."},
            {"name": "Hanga Vare Vare", "type": "cultural", "lat": -27.1450, "lng": -109.4320, "description": "Explanada ceremonial de la fiesta Tapati Rapa Nui."},
            {"name": "Caleta Hanga Piko", "type": "cultural", "lat": -27.1573, "lng": -109.4374, "description": "Puerto de cargas con el Ahu Riata restaurado."},
            {"name": "Punto de surf Hanga Roa", "type": "mirador", "lat": -27.1490, "lng": -109.4345, "description": "Observa a los surfistas locales en olas de clase mundial."},
        ],
        "vai": {
            "recommended_liters": "1 litro por persona",
            "buy_point_ids": ["vai-1", "vai-2"],
            "tips": [
                "Hay almacenes a pocos metros de la costanera: aprovecha de comprar agua VAINATIVA fría.",
                "Si vas al atardecer, lleva agua igualmente: la brisa marina deshidrata sin que lo notes.",
            ],
        },
    },
    {
        "id": "ana-kai-tangata",
        "name": "Sendero Ana Kai Tangata",
        "type": "urbana",
        "distance_km": 4.0,
        "duration_min": 90,
        "difficulty": "Fácil",
        "color": "#4A6B53",
        "image": IMG_TRAIL,
        "summary": "Desde el centro de Hanga Roa hasta la cueva marina con pinturas rupestres del culto al hombre-pájaro.",
        "description": "Ruta urbana registrada que sale del centro de Hanga Roa hacia el sur, bordeando el sector de Mataveri hasta llegar a Ana Kai Tangata, una espectacular cueva marina de 15 metros de ancho excavada por el oleaje en la lava. En su techo se conservan pinturas rupestres de manutara (gaviotín pascuense) en rojo, blanco y negro, vinculadas al culto del Tangata Manu (hombre-pájaro). El nombre se traduce como 'cueva donde los hombres comen'. El acceso baja por una escalera tallada en la roca; con marejada, observa solo desde el mirador superior.",
        "path": [
            [-27.1499, -109.4335], [-27.1530, -109.4340], [-27.1560, -109.4355],
            [-27.1600, -109.4380], [-27.1640, -109.4410], [-27.1670, -109.4440],
        ],
        "pois": [
            {"name": "Cueva Ana Kai Tangata", "type": "cueva", "lat": -27.1670, "lng": -109.4440, "description": "Pinturas rupestres del manutara sobre techo de lava."},
            {"name": "Mirador Mataveri", "type": "mirador", "lat": -27.1620, "lng": -109.4400, "description": "Vista de la pista de aterrizaje más remota del mundo."},
        ],
        "vai": {
            "recommended_liters": "1,5 litros por persona",
            "buy_point_ids": ["vai-1", "vai-5"],
            "tips": [
                "El Minimarket del sector Mataveri es el último punto para comprar agua VAINATIVA antes de la cueva.",
                "No hay sombra en el tramo final: lleva sombrero y protector solar.",
            ],
        },
    },
    # ---------------- RURALES ----------------
    {
        "id": "rano-kau-orongo",
        "name": "Rano Kau y Aldea Ceremonial Orongo",
        "type": "rural",
        "distance_km": 9.0,
        "duration_min": 210,
        "difficulty": "Moderada",
        "color": "#8A4A3B",
        "image": IMG_MOAI,
        "summary": "Ascenso por el sendero Te Ara o Te Ao al cráter del volcán Rano Kau y la aldea del hombre-pájaro.",
        "description": "La ruta rural más emblemática del sur parte desde Hanga Roa por el sendero patrimonial Te Ara o Te Ao ('el camino del Ao', el remo ceremonial de mando). Asciende entre guayabos y eucaliptos hasta el borde del cráter del volcán Rano Kau, de 1,6 km de diámetro, cuya laguna interior cubierta de totora es uno de los tres humedales de la isla. El sendero bordea el cráter hasta Orongo, la aldea ceremonial de 53 casas de piedra laja donde se celebraba la competencia del Tangata Manu: los jóvenes descendían el acantilado de 300 metros y nadaban hasta el motu Nui en busca del primer huevo del manutara. Requiere ticket del Parque Nacional Rapa Nui.",
        "path": [
            [-27.1524, -109.4327], [-27.1570, -109.4345], [-27.1620, -109.4360],
            [-27.1680, -109.4355], [-27.1730, -109.4345], [-27.1770, -109.4340],
            [-27.1820, -109.4370], [-27.1860, -109.4410], [-27.1885, -109.4430],
        ],
        "pois": [
            {"name": "Mirador cráter Rano Kau", "type": "mirador", "lat": -27.1770, "lng": -109.4340, "description": "Laguna del cráter con microclima propio, de 1,6 km de diámetro."},
            {"name": "Aldea Ceremonial Orongo", "type": "arqueologico", "lat": -27.1885, "lng": -109.4430, "description": "53 casas de piedra del culto Tangata Manu y petroglifos de Make Make."},
            {"name": "Mirador Motu Nui", "type": "mirador", "lat": -27.1890, "lng": -109.4415, "description": "Vista de los tres motu donde anidaba el manutara."},
            {"name": "Sendero Te Ara o Te Ao", "type": "cultural", "lat": -27.1680, "lng": -109.4355, "description": "Camino ceremonial ancestral de los participantes del rito."},
        ],
        "vai": {
            "recommended_liters": "2,5 litros por persona",
            "buy_point_ids": ["vai-1", "vai-5"],
            "tips": [
                "NO hay venta de agua en Orongo ni en el cráter: compra toda tu agua VAINATIVA en Hanga Roa o Mataveri.",
                "El ascenso es exigente con calor: sal antes de las 9:00 y bebe 250 ml cada 20 minutos.",
                "La laguna del cráter NO es apta para beber ni para acercarse: es zona protegida.",
            ],
        },
    },
    {
        "id": "anakena-ovahe",
        "name": "Playa Anakena y Ovahe",
        "type": "rural",
        "distance_km": 4.0,
        "duration_min": 90,
        "difficulty": "Fácil",
        "color": "#D4A373",
        "image": IMG_WATER,
        "summary": "Las dos playas de arena coralina del norte, con el Ahu Nau Nau y sus moai mejor conservados.",
        "description": "Anakena es la playa histórica donde, según la tradición oral, desembarcó el ariki Hotu Matu'a para fundar el pueblo rapanui. Arena de coral blanco, palmeras cocoteras traídas de Tahití y aguas turquesas de 20-24°C todo el año. Frente a la playa se alza el Ahu Nau Nau, con siete moai que conservan sus pukao (moños de escoria roja) y finos petroglifos en la espalda, protegidos siglos bajo la arena. La caminata continúa 1,5 km por el sendero costero hasta Ovahe, una playa virgen de arena rosada al pie de un acantilado volcánico. Cuidado con la marea en Ovahe.",
        "path": [
            [-27.0730, -109.3230], [-27.0720, -109.3200], [-27.0700, -109.3180],
            [-27.0680, -109.3165], [-27.0665, -109.3155],
        ],
        "pois": [
            {"name": "Playa Anakena", "type": "playa", "lat": -27.0730, "lng": -109.3230, "description": "Playa fundacional de Hotu Matu'a, con palmeras y aguas turquesa."},
            {"name": "Ahu Nau Nau", "type": "moai", "lat": -27.0725, "lng": -109.3245, "description": "Siete moai con pukao y petroglifos, los mejor conservados de la isla."},
            {"name": "Ahu Ature Huki", "type": "moai", "lat": -27.0735, "lng": -109.3225, "description": "Primer moai re-erguido (1956) por Thor Heyerdahl con 12 isleños."},
            {"name": "Playa Ovahe", "type": "playa", "lat": -27.0665, "lng": -109.3155, "description": "Playa escondida de arena rosada bajo un acantilado de escoria."},
        ],
        "vai": {
            "recommended_liters": "2 litros por persona",
            "buy_point_ids": ["vai-4", "vai-1"],
            "tips": [
                "El Kiosco de Anakena es el ÚNICO punto de venta de agua fuera de Hanga Roa: no siempre abre en temporada baja.",
                "Lleva agua VAINATIVA de respaldo desde Hanga Roa: son 18 km sin ningún otro abastecimiento.",
                "Después de nadar en agua salada la deshidratación aumenta: bebe apenas salgas del mar.",
            ],
        },
    },
    {
        "id": "rano-raraku-tongariki",
        "name": "Rano Raraku y Ahu Tongariki",
        "type": "rural",
        "distance_km": 3.0,
        "duration_min": 120,
        "difficulty": "Moderada",
        "color": "#B35D4A",
        "image": IMG_MOAI,
        "summary": "La cantera donde nacieron los moai y la plataforma ceremonial más grande de la Polinesia.",
        "description": "Rano Raraku es la 'fábrica de los moai': en las laderas de toba volcánica de este cráter se tallaron el 95% de los 900 moai de la isla. Casi 400 estatuas permanecen aquí en todas las etapas de tallado, incluido El Gigante, un moai inconcluso de 21 metros. El sendero interior rodea la laguna del cráter entre totorales. A 1 km, el Ahu Tongariki es la plataforma ceremonial más monumental de la Polinesia: 15 moai de hasta 86 toneladas re-erguidos tras el maremoto de 1960 que los arrastró 100 metros tierra adentro. Al amanecer, el sol sale exactamente detrás de los 15 moai durante el solsticio de verano. Requiere ticket del Parque Nacional (una sola entrada por sitio).",
        "path": [
            [-27.1215, -109.2885], [-27.1230, -109.2860], [-27.1245, -109.2830],
            [-27.1250, -109.2800], [-27.1258, -109.2768],
        ],
        "pois": [
            {"name": "Cantera Rano Raraku", "type": "arqueologico", "lat": -27.1215, "lng": -109.2885, "description": "397 moai en la ladera, incluido el moai arrodillado Tukuturi."},
            {"name": "Moai El Gigante", "type": "moai", "lat": -27.1210, "lng": -109.2875, "description": "Moai inconcluso de 21,6 m y 270 toneladas, aún unido a la roca."},
            {"name": "Ahu Tongariki", "type": "moai", "lat": -27.1258, "lng": -109.2768, "description": "15 moai monumentales; el mejor amanecer de la isla."},
            {"name": "Moai Viajero", "type": "moai", "lat": -27.1262, "lng": -109.2790, "description": "Moai que viajó a Japón en 1982; hoy saluda a la entrada de Tongariki."},
        ],
        "vai": {
            "recommended_liters": "2 litros por persona",
            "buy_point_ids": ["vai-7", "vai-1", "vai-3"],
            "tips": [
                "Estás a 20 km de Hanga Roa: compra agua VAINATIVA antes de salir del pueblo o en los locales del sector Rano Raraku.",
                "Para ver el amanecer en Tongariki llega 6:30; lleva agua y abrigo, el viento es fuerte.",
                "En la cantera no hay sombra: hidrátate antes de sentir sed.",
            ],
        },
    },
    {
        "id": "terevaka",
        "name": "Ascenso al Maunga Terevaka",
        "type": "rural",
        "distance_km": 10.0,
        "duration_min": 240,
        "difficulty": "Difícil",
        "color": "#9E4747",
        "image": IMG_TRAIL,
        "summary": "La cumbre de la isla (511 m): vista de 360° donde se siente la redondez de la Tierra.",
        "description": "El Maunga Terevaka es el volcán más alto y joven de Rapa Nui (511 msnm). La ruta registrada parte desde Ahu Akivi y sube por praderas de pasto ondulante donde pastan caballos salvajes. Desde la cumbre se observa la isla completa y un horizonte de océano en los 360°: es el punto donde muchos visitantes dicen 'sentir la curvatura de la Tierra', con la tierra habitada más cercana a 2.075 km (Pitcairn). No hay sombra en ningún tramo de la ruta y el viento en la cumbre puede superar los 50 km/h. Se puede hacer a pie o a caballo con guías locales.",
        "path": [
            [-27.1150, -109.3947], [-27.1110, -109.3920], [-27.1060, -109.3890],
            [-27.1010, -109.3860], [-27.0960, -109.3830], [-27.0920, -109.3805],
            [-27.0885, -109.3790],
        ],
        "pois": [
            {"name": "Cumbre Maunga Terevaka", "type": "mirador", "lat": -27.0885, "lng": -109.3790, "description": "511 msnm, vista de 360° de toda la isla y el Pacífico infinito."},
            {"name": "Cráter Rano Aroi", "type": "mirador", "lat": -27.0930, "lng": -109.3760, "description": "Pequeño humedal de altura, una de las 3 reservas de agua dulce."},
            {"name": "Praderas de caballos salvajes", "type": "cultural", "lat": -27.1010, "lng": -109.3860, "description": "Miles de caballos en libertad pastan en las laderas."},
        ],
        "vai": {
            "recommended_liters": "3 litros por persona",
            "buy_point_ids": ["vai-1", "vai-3"],
            "tips": [
                "Ruta SIN ningún punto de agua: carga 3 litros de agua VAINATIVA por persona desde Hanga Roa.",
                "Cero sombra en 10 km: sal antes de las 8:00, usa sombrero, mangas largas y factor 50+.",
                "El humedal Rano Aroi NO es apto para beber: es reserva protegida de agua de la isla.",
                "Si sientes dolor de cabeza o mareo, es deshidratación: bebe, descansa y desciende.",
            ],
        },
    },
    {
        "id": "akivi-ana-te-pahu",
        "name": "Ahu Akivi y Cuevas Ana Te Pahu",
        "type": "rural",
        "distance_km": 6.0,
        "duration_min": 150,
        "difficulty": "Moderada",
        "color": "#4A6B53",
        "image": IMG_MOAI,
        "summary": "Los siete exploradores que miran al mar y el mayor sistema de cuevas-jardín de la isla.",
        "description": "El Ahu Akivi es único: sus siete moai son los únicos que miran hacia el océano, alineados astronómicamente con el equinoccio. La tradición los identifica con los siete exploradores que Hotu Matu'a envió a reconocer la isla antes de la colonización. La ruta continúa hacia Ana Te Pahu, el sistema de tubos de lava más extenso de la isla (7 km de galerías), usado ancestralmente como vivienda y refugio. En sus bocas abiertas los rapanui cultivaban manavai: jardines hundidos con plátanos, taro y ñame que aún crecen protegidos del viento y la sal. Lleva linterna para recorrer las galerías.",
        "path": [
            [-27.1150, -109.3947], [-27.1130, -109.3960], [-27.1100, -109.3975],
            [-27.1075, -109.3980], [-27.1060, -109.3980],
        ],
        "pois": [
            {"name": "Ahu Akivi", "type": "moai", "lat": -27.1150, "lng": -109.3947, "description": "Los 7 exploradores: únicos moai orientados hacia el mar."},
            {"name": "Cuevas Ana Te Pahu", "type": "cueva", "lat": -27.1060, "lng": -109.3980, "description": "7 km de tubos volcánicos con jardines manavai de plátanos."},
            {"name": "Manavai (jardines de piedra)", "type": "arqueologico", "lat": -27.1070, "lng": -109.3975, "description": "Técnica agrícola ancestral en círculos de piedra."},
        ],
        "vai": {
            "recommended_liters": "2 litros por persona",
            "buy_point_ids": ["vai-1", "vai-3"],
            "tips": [
                "Sin puntos de venta en la ruta: abastécete de agua VAINATIVA en los almacenes de Av. Atamu Tekena.",
                "Dentro de las cuevas la temperatura baja, pero el trayecto entre sitios es a pleno sol.",
                "No toques los plátanos de los manavai: son sitios arqueológicos vivos.",
            ],
        },
    },
    {
        "id": "peninsula-poike",
        "name": "Península del Poike",
        "type": "rural",
        "distance_km": 12.0,
        "duration_min": 300,
        "difficulty": "Difícil",
        "color": "#8A4A3B",
        "image": IMG_TRAIL,
        "summary": "El extremo este y más antiguo de la isla: acantilados, el moai sonriente y la leyenda de la zanja de los Hanau Eepe.",
        "description": "El Poike es el volcán más antiguo de Rapa Nui (3 millones de años) y forma la península oriental de la isla, delimitada por la legendaria 'zanja del Poike' donde según la tradición oral ocurrió la batalla entre los clanes Hanau Eepe y Hanau Momoko. Esta ruta rural exigente y poco transitada recorre acantilados de 150 metros, la cima del Maunga Pu A Katiki (400 msnm) y rincones ocultos como el moai sonriente de Ana O Keke y la cueva de las vírgenes, con petroglifos vinculados al ritual del neru. Es obligatorio ir con guía local: la ruta no está señalizada y los acantilados son peligrosos.",
        "path": [
            [-27.1050, -109.2600], [-27.1020, -109.2560], [-27.0990, -109.2510],
            [-27.0980, -109.2460], [-27.1010, -109.2420], [-27.1060, -109.2400],
            [-27.1110, -109.2430], [-27.1140, -109.2490],
        ],
        "pois": [
            {"name": "Maunga Pu A Katiki", "type": "mirador", "lat": -27.0980, "lng": -109.2460, "description": "Cima del volcán más antiguo, 400 msnm de praderas doradas."},
            {"name": "Moai sonriente (Ana O Keke)", "type": "moai", "lat": -27.1010, "lng": -109.2420, "description": "Pequeño moai con una insólita sonrisa tallada, escondido en el este."},
            {"name": "Cueva de las Vírgenes", "type": "cueva", "lat": -27.0950, "lng": -109.2440, "description": "Cueva del ritual neru con petroglifos; acceso solo con guía."},
            {"name": "Acantilados del Poike", "type": "mirador", "lat": -27.1140, "lng": -109.2490, "description": "Paredones de 150 m donde revientan las olas del Pacífico."},
        ],
        "vai": {
            "recommended_liters": "3,5 litros por persona",
            "buy_point_ids": ["vai-1"],
            "tips": [
                "La ruta más remota de la guía: carga 3,5 litros de agua VAINATIVA por persona, sin excepción.",
                "Contrata guía local: incluye normalmente transporte y agua adicional, confírmalo antes.",
                "No hay señal de celular en gran parte del Poike: avisa tu ruta antes de salir.",
                "Guarda 1 litro de reserva para el regreso: el viento del este deshidrata rápidamente.",
            ],
        },
    },
    {
        "id": "costa-norte",
        "name": "Costa Norte: Tahai a Anakena",
        "type": "rural",
        "distance_km": 14.0,
        "duration_min": 360,
        "difficulty": "Difícil",
        "color": "#607D8B",
        "image": IMG_TRAIL,
        "summary": "La travesía costera salvaje: cuevas Ana Kakenga y Ana Te Pora, ahu caídos y caletas vírgenes hasta Anakena.",
        "description": "La gran travesía de Rapa Nui: 14 km por la costa noroeste sin caminos vehiculares, desde Tahai hasta la playa Anakena. El sendero pasa por Ana Kakenga, la 'cueva de las dos ventanas' cuyo túnel de 50 metros desemboca en dos balcones sobre el acantilado; Ahu Te Peu, con los cimientos de la casa-bote del último rey; y Ana Te Pora, una caverna con plataforma ceremonial interior. En el tramo final aparecen caletas vírgenes, ahu con moai caídos boca abajo tal como quedaron tras el Huri Moai (época de derribamiento) y colonias de aves marinas. Termina con un baño merecido en Anakena. Solo para caminantes experimentados: sin sombra, sin agua y sin señal en la mayor parte del trayecto.",
        "path": [
            [-27.1355, -109.4265], [-27.1250, -109.4300], [-27.1150, -109.4320],
            [-27.1030, -109.4310], [-27.0940, -109.4230], [-27.0870, -109.4120],
            [-27.0800, -109.4000], [-27.0740, -109.3850], [-27.0690, -109.3680],
            [-27.0660, -109.3500], [-27.0680, -109.3350], [-27.0730, -109.3230],
        ],
        "pois": [
            {"name": "Cueva Ana Kakenga", "type": "cueva", "lat": -27.1030, "lng": -109.4310, "description": "Túnel de lava con dos 'ventanas' colgadas sobre el mar."},
            {"name": "Ahu Te Peu", "type": "arqueologico", "lat": -27.0980, "lng": -109.4270, "description": "Cimientos de hare paenga (casa-bote) del último ariki."},
            {"name": "Cueva Ana Te Pora", "type": "cueva", "lat": -27.0940, "lng": -109.4230, "description": "Caverna amplia con plataforma de piedra ceremonial."},
            {"name": "Caleta Hanga Oteo", "type": "playa", "lat": -27.0740, "lng": -109.3850, "description": "Bahía virgen con colonias de aves y piscinas de marea."},
            {"name": "Playa Anakena", "type": "playa", "lat": -27.0730, "lng": -109.3230, "description": "Final de la travesía: baño en aguas turquesa junto a los moai."},
        ],
        "vai": {
            "recommended_liters": "4 litros por persona",
            "buy_point_ids": ["vai-1", "vai-3", "vai-4"],
            "tips": [
                "La ruta más larga de la guía: 4 litros de agua VAINATIVA por persona es el mínimo seguro.",
                "El Kiosco de Anakena al final del recorrido vende agua fría, pero NO dependas de él: confirma horario.",
                "Congela 2 botellas la noche anterior: se descongelan en ruta y mantienen el agua fresca.",
                "Coordina transporte de regreso desde Anakena: no querrás caminar de vuelta.",
            ],
        },
    },
    {
        "id": "vinapu",
        "name": "Ruta Vinapu y Costa Sur",
        "type": "rural",
        "distance_km": 5.5,
        "duration_min": 120,
        "difficulty": "Fácil",
        "color": "#D4A373",
        "image": IMG_MOAI,
        "summary": "El enigmático muro 'inca' de Vinapu y los ahu de la costa sureste.",
        "description": "Partiendo del sector de Mataveri, esta ruta rural corta bordea la costa sur hasta el complejo Vinapu, famoso por el Ahu Tahira: un muro de bloques de basalto finamente ensamblados que recuerda a la arquitectura inca del Cusco, alimentando décadas de debate arqueológico sobre contactos entre la Polinesia y Sudamérica. El sitio incluye un raro moai femenino de columna roja que servía de pilar ceremonial. La costa sur ofrece acantilados bajos, bufaderos donde el mar explota entre las rocas y vista permanente al perfil del Rano Kau.",
        "path": [
            [-27.1580, -109.4360], [-27.1620, -109.4300], [-27.1650, -109.4230],
            [-27.1670, -109.4160], [-27.1685, -109.4100],
        ],
        "pois": [
            {"name": "Ahu Tahira (Vinapu I)", "type": "arqueologico", "lat": -27.1685, "lng": -109.4100, "description": "Muro de basalto de precisión 'incaica', enigma arqueológico."},
            {"name": "Moai femenino de Vinapu", "type": "moai", "lat": -27.1683, "lng": -109.4105, "description": "Raro moai de escoria roja con dos cabezas, posiblemente femenino."},
            {"name": "Bufaderos costa sur", "type": "mirador", "lat": -27.1650, "lng": -109.4230, "description": "Chorros de mar que explotan entre grietas de lava."},
        ],
        "vai": {
            "recommended_liters": "1,5 litros por persona",
            "buy_point_ids": ["vai-5", "vai-1"],
            "tips": [
                "Compra agua VAINATIVA en el minimarket de Mataveri al inicio de la ruta.",
                "Ruta expuesta al viento sur: aunque se sienta fresco, bebe cada 30 minutos.",
            ],
        },
    },
]
